# Default connection settings
[connection]
base_delay = 1
max_delay = 60
max_retries = -1

# Endpoints configuration
[[endpoints]]
name = "default"
server = "ws://localhost:3000"
secret = "your-secret-here"
enabled = true

# Optional override for this endpoint
[endpoints.connection]  # Override default connection settings
base_delay = 2
max_delay = 30
max_retries = 3

[[endpoints]]
name = "backup"
server = "wss://backup.example.com/ws"
secret = "your-backup-secret-here"
enabled = true
# This endpoint will use the default settings since no overrides are specified
